version: "2"
services:
  nginxproxy:
    image: nginx-vnc-cloud:latest
    ports:
      - "8080:80"
    restart: always
  serverserverproxy:
    image: serverserver:latest
    ports:
      - "5000:80"
      - "5900:5900"
    restart: always
  novnc:
    image: novnc:latest
    ports:
      - "6080:6080"
    restart: always
  